comment: false

coverage:
  status:
    project:
      default:
        threshold: "3%"
        target: "auto"
      minimum:
        target: "50%"
    patch:
      default:
        threshold: "3%"
        target: "auto"
