## This file auto-generated by Yggdrasil/build_hashes.jl
shard_hash_table = Dict{CompilerShard,String}(
    CompilerShard("Rootfs", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz)
      => "09ca76f2134de87185b87ed20fe288a66b854fad199866806208809731c51873",
    CompilerShard("Rootfs", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs)
      => "225166fd5d70020e921187e121283b2dcd0dff586ecb6caecd2190277d66cb52",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-gnu"))
      => "685162b4f555ab1fa3ff81f8d004bf2df32462cac044ef76f0ddf14eda09979c",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-gnu"))
      => "401802a766740e028118308906aec1e79c2addb19a367f48f994c085002bed0b",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-musl"))
      => "861f7145e93c08feea92bce29dbebce20a25e78f375017655a4373708ad9c068",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-musl"))
      => "993658488b0bf8e49101e902d4a606cc5fcde259209f2f7e789354e24c055eac",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-gnueabihf"))
      => "12ec57804907fd358a6692b96a005b25ebfd6bd390f44176955f50fca67798af",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-gnueabihf"))
      => "7449c83b7f8909cf96ab83bdb1ec2598e4b4e9b881653ca53b80c8ac02c9c26e",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-musleabihf"))
      => "1a0dce4fe05ca7b397602da57f0ee30684c228900116f87aded961996549f87a",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-musleabihf"))
      => "f81e4ab7259f7272b0a79f2b3e0fa3632c8bd98461318b999b2de20f49ed7d57",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-gnu"))
      => "5f7005c3cb99db1595a55ae9d1b5ab929769b084e450a19903d88352b5f94a6d",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-gnu"))
      => "eaf774889eda1bd684b41bc6b4ca032ab2d22a28c770dd1bbf85edb49ce823d9",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-musl"))
      => "0a96482eac30e8ae80fd2298902284677ae5a9aff17cb174e7337af6d5019663",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-musl"))
      => "18fa0c72c497ec56f8af99fb8c4bf7d889a8193b1d52238c4451e6338aea2d62",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-w64-mingw32"))
      => "07e7c4e1a5063b157c832dbc66ddeed3053371eb6198f366b5e3d96df99c2a40",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-w64-mingw32"))
      => "43ac7c039c989fbfeff3bb1b339c030b280ef6e9e48b5daa625f091b6851e2c0",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "5165942fb2f471c71492b0511b33fb401f131dd4c0a5f0d973cfaa6ea52937c0",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "cfab5e484a089876c4bb9be1b1e487f67dcd0bd38a08050c195805a55ca9da34",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-apple-darwin14"))
      => "fbeafdbce19169340b30d80d83710eb38faf9f8490faaa5c292e07e1d3ac5133",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-apple-darwin14"))
      => "2c169752eccbfb2d90f6abf66551b0a595585ece1009b7aea0b76cf7fb88ae40",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-gnu"))
      => "ca3173a11b7f14ed1e1f4e9b8d27e62937e393381de63b35f050bf9658ffdea4",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-gnu"))
      => "414f20b02f0aa350b99e1417acde0bb0d8788009949e402c5f8460974f0cb4dd",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-musl"))
      => "23540a895bc09decbebf22c4415c2c1cf149b22ee1b7860a93358c04801d582d",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-musl"))
      => "321f18520d36dfba35cfd32749f298ea4c5b67acca9303b411b6a28e8c4abc94",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "9902b928841df9c40484c17eab3ab5ba4b8286b0e6abb6865999f28cd126f0d6",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "cbd28ddfd0f42b585d61ad0ce3cd30b0c93c51215431f3c745b5747764d454bb",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-w64-mingw32"))
      => "6cb78cd04731f0c9ebad911da06a02f8535c1bb076af194164aef776cd4158f8",
    CompilerShard("BaseCompilerShard", v"2018.9.18", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-w64-mingw32"))
      => "3d6141d325e2c33dc41a98714a3733bdcb35557cd90d8a533ecfb7fb71312204",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-gnu"))
      => "805c2ae8562a51945b8b6a6c263f20ee52d110891e7799b21093750730cb74c7",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-gnu"))
      => "727be698216c43199b730c84de01b160ed4d83c2d176b07a9949bf17a9c9a9be",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-gnu"))
      => "00d19deb7a9ac79505d7ffd48b6bf86a82b82ec77436751872d37b7acf53b725",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-gnu"))
      => "70fda2388e9c74c0e05ff1810faca532bec4ecd49c7550f9f1b72b9ac81f797f",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-gnu"))
      => "d8931c2b598562dddf5cb60fec1f39a5c1ca187d42dad744d1bdbfc7b6d9f9ba",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-gnu"))
      => "9d74a42210e42b607c91ca16d94b0530825eae416e287601eea7ee312caf02ac",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-musl"))
      => "e1230183f44b3b2aa9e7462322e0fa06fc5584fec3233758a548a88fa47df074",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-musl"))
      => "49cab4b5fdb8a8eaf2d4551ab6e3f9f501eeda5909d02179e3502d9d3871cf92",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-musl"))
      => "ab93bb13f68cbd733f3196e58e0b99838201aa15f81fe110ef3ad3fbb7de4cf8",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-musl"))
      => "a65bb81dde47704221960c69e3cede330de52db88dd50ce5bad6cc7e5d16ae83",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("aarch64-linux-musl"))
      => "269e2b68de0b5ed0ae9a612b4885f8d69acc8eed0d7e44527da5a8c546ab8f3d",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("aarch64-linux-musl"))
      => "e337851acabab44a9c66fa075569a71480b6ea6d7e8e17081985e97cfa06e044",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-gnueabihf"))
      => "a775a17c89575938345a0a33eaa86fcbb58ed38f7c13072e3ad2eb166463749b",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-gnueabihf"))
      => "ce31f00c378627746f6c404064991d680f357db07cf1ced9fdf47a42f0b5fd0f",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-gnueabihf"))
      => "3c06e0dd811c3fa86a21d1286beeb47ef7c144873bf8b9d6f2dfcf130fb5e1cc",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-gnueabihf"))
      => "d926f4aa8fec3cb4c2468c3970ec9c815c3b6fcf29c46d5abe653770dce31ba6",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-gnueabihf"))
      => "90469f4863c425e5e4e488f445ecdd252db428ce67c527107e0ed4c1c9c6d4d1",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-gnueabihf"))
      => "074e108776b699b77eef886c8308d5e4b17a83549068dd0ad1f0410c8c05cf33",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-musleabihf"))
      => "070f3bca044cc6268fbad762fade04ac84ef31620fe08812c9efaf4dc1aced2a",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-musleabihf"))
      => "a955805f16b621021607b0d22f6d892757ab1d076120fcf718a87712d279459b",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-musleabihf"))
      => "9b83746ecb5ac3de1b71ad4679a23cfbafb314340d1e173a3b90c5c6a55dc84e",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-musleabihf"))
      => "40649207e3e95021c324ceca02d30f64c01c5f8f8a63e79e26061274bd36e2ab",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("arm-linux-musleabihf"))
      => "dfae9a7ecdce8bbeca99c85f769074cd8da018a45e5a1dffe7aab6c6d01de22d",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("arm-linux-musleabihf"))
      => "8f1ca5b0ae46555001d3097be7882295d41b8b2b641c33eeb14a9972625479d4",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-gnu"))
      => "33c400654f8d6fdd16a8cdaf9d7348f8133ef7e169976414a7ebe43d425c33bb",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-gnu"))
      => "85f706e236f2c36ac98d1159eae6ca6ada1faa89468c0f3598cfe87cfc62d688",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-gnu"))
      => "b071a9b3dbf9532d691127dbe5bb3599ba963b930593ca018af8f4290fe2575f",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-gnu"))
      => "568ae1954185883b08c11e268e869e2dbaf2fb8d4511fe7c2990c6ba46f80de3",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-gnu"))
      => "74ae1cdc2d4e634d9eb5b21b4f505ffc2239c43511496c80e4e6620e0d0ac467",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-gnu"))
      => "5ba41393f6762b0007298470fd5392850e439ba721602a1e2a8d08e5e5cbd192",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-musl"))
      => "8a1a671a755a5b800f88a6869dba09b29f9f687051303dbbe4ed7ea4a38cc615",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-musl"))
      => "8269129795cafdac88c0214d79ae99da354eaf0581958d6121297ae7e824fbfe",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-musl"))
      => "66546aac3a9a8c8a71a88c0f8e73460d957096f1887277f96efe857b8dd8f5fa",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-musl"))
      => "9167296c93526121529e05d95401b9c0a955d5b1b2663c4911af3e506db44ecb",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-linux-musl"))
      => "8c56c53a133456381926ba69a521bf3c7fa7c33db04041700f114c80161226e7",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-linux-musl"))
      => "d04941f924ae59636d6d86311554fd8f79d54d666b11afc0f877d310c4f7c02a",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-w64-mingw32"))
      => "e77919a8592341bdd6bff320b795a2109e21800185a6be29fd738aedb38bfc84",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-w64-mingw32"))
      => "bfdfc2dd2f07d68b7e5b1f60420ca953bfa1d156548a8536fb8773ce4f1388e6",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-w64-mingw32"))
      => "d80c2f0826c6148a9a2dfb6d090039a0cd7daf02798014dcf8d5f379a139612f",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-w64-mingw32"))
      => "12a0e2fcab2f8264f789a58e9ca9b58e491f58c134684a32c5c6af1db506baaa",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("i686-w64-mingw32"))
      => "2eb7602ef8b5c1f7d31f48786b55e23788ad26a3cda0af876a79ac53e1a126e5",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("i686-w64-mingw32"))
      => "7c1bca1273d68b4d4405d0b9423288c0f4c6748bce0d5485101d9668f0e90f04",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "2f03a420e6db1a9b1d6c1251166bd542b561331e13e9276ae02632d6dc4cfa0c",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "72620dbc6d00bca2c43334c8a7c7910e1545451dbf97bbf022d63aeda446d876",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "7846ccb2e1162f8b7f575bb202ef8824cd543750ba98074f0c3d3c20a2a2b1c1",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "ad15632f1ced9b844884ba6289c08bc30e725ca9b2656016d04a988109ee1d05",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "c5d3df2fb165d5ee7b168f2912f924cb06ae0df033e300651a8ee8a4e2792594",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("powerpc64le-linux-gnu"))
      => "0c259429e649441b91e7784ed8ff2d2d634af4a79fc16bf4f6a2546caa616485",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-apple-darwin14"))
      => "988f5b33cbc6ee9560fcf4dfedc8e3130f98f586ee24c2d7f3fc888beb3aa7df",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-apple-darwin14"))
      => "2b0a722688afeaf9ed6b7e05e8cbea7368d7921deff2a742a7146774d23c6800",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-apple-darwin14"))
      => "1b6b47071ba3cb9b7732fd9c8cdb6ff02d1cf7ff8200da74310815b0eeb0b30c",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-apple-darwin14"))
      => "dc66edfd3963eaf08d58e55d72652ea09c7548faae314d7ba80c9c05ec38ef47",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-apple-darwin14"))
      => "1df741772e611fbc6336958929bc37393f1f5588cac428ac832c26ca944c0a14",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-apple-darwin14"))
      => "9fd1f8aa9835351397452188ad727334873e5fda9679291a2ba14e3748a988f8",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-gnu"))
      => "c2929282ea8f757369dfbc5499593565ade235052660a5675e7e84d9c577d79e",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-gnu"))
      => "223073385f4829ba7066553eb5635566db119be0d51bbb607d70fa5a44dac449",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-gnu"))
      => "0d0f35d49080cc199eb50369948f7757ef34dc11d62a0c927a9f88ea5335d574",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-gnu"))
      => "c8e0d4211c5bdf7d0eaa080498b0eb5994bf5a22f674d620bb50509c43dfe385",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-gnu"))
      => "5a795ade80e4623cb20122e110abe121d34e50becc490321a2427ab6fb209a6a",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-gnu"))
      => "b537f0dcb407504ee4375a08e5490e1558adcbad99c1bf491cff32eb3008f920",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-musl"))
      => "7b6f0ad6c414afd3552850debf272dd6411131b26e621d60ff0047649925e578",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-musl"))
      => "df5f4d790c40e5ba2c44cb7bb27325092c5eb3f21fb21188e31611cba8fd6b3a",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-musl"))
      => "c17dc5eeebb307ae8da514ac9adbfb4ee0e3952f7262dcd53d3c8624e109b6bf",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-musl"))
      => "823be423cea868df4eb23a2426e26112f9381f1388091aea410e8325a3f80471",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-linux-musl"))
      => "32370b97fc164be7624dce792fd9c08a9ee30ce214f899015eedfbbc0e30b3bb",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-linux-musl"))
      => "874dfe5d4150018bfcfb2360c8c2c3420ccdcb838860b723468170aafef5407a",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "84f05dcdc5ba04346c52d2fed4e0c044e0fcc315cc2e5ba1026f98cfd0d2b72d",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "035ce50908500b546ccce7ae42ab1427a7b46f69b2cebf375ad60f21b1aab0a1",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "fe8f3f6cd5ec91583f96b8e077d63cd0c7de4e4c2afdb1f302ac9c4bc8088811",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "3ddf4860b8954f7cd9f2d33156a4825563a9564b1a145870ea865363d4920083",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "6daf98e374ec30317338330735ae1be4151a21f6264e8e390890aa7901e8e588",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-unknown-freebsd11.1"))
      => "1b23c273a47da39f8a674bd65af565862f1cea2651549b2dc5c28b8ca6add3b7",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-w64-mingw32"))
      => "e7c53ca794f8ac674e2d9c18879575887d595cbb38c5e7357e9eae17d23791c4",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-w64-mingw32"))
      => "fb262e83559d799cab12963bc603058d8eec163a246dda512e4bd3a108b8e75c",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-w64-mingw32"))
      => "483b2586fbe7c1939e068b7c2fe7237db45c797bce3be932bf86fd741a2b0a3f",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-w64-mingw32"))
      => "cdd907ee2c8a89650a0b5d041b923c9ef91a8ef91d8bdbc407dae8a1d0f528bc",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz; target=platform_key_abi("x86_64-w64-mingw32"))
      => "e84ddd12f798531d02048c10628402947d5587da978fc1d3d89dbdfee45b907a",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs; target=platform_key_abi("x86_64-w64-mingw32"))
      => "2af59fbd5668a570f59aeedfb83fdb74be7b7d0c51408553cacd9808088bb6cf",
    CompilerShard("LLVM", v"6.0.1", Linux(:x86_64, libc=:glibc), :targz)
      => "72c383dc42eaee7d6ee64b1cd34540dcea0217ce17b7eb121b706138c515e58a",
    CompilerShard("LLVM", v"6.0.1", Linux(:x86_64, libc=:glibc), :squashfs)
      => "f246f422e7b9f921de3c01b77c838a85e6a537eb103d16d5fef8c7149a7b0942",
)
