## This file auto-generated by deps/build_hashes.jl
shard_hash_table = Dict{CompilerShard,String}(
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:aarch64, libc=:glibc), :targz)
      => "5deeb49fc28d8fbda3d94e6b40372243a0e0c18713b880ffc686db2d431637ca",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:aarch64, libc=:glibc), :squashfs)
      => "4f7975dd41bf687698cbdc0fbfa1143459913442803778f5181efe9bbe0d9b46",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:aarch64, libc=:musl), :targz)
      => "cf0a08b1a7692a6c89ce9bee6f8161c1edddf6f0d29dcf5818734e90c6472a94",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:aarch64, libc=:musl), :squashfs)
      => "9a1e90509602414233f3668778652f8c2fc03fbacad762f2372d1837dc7a0e8c",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :targz)
      => "dca77e3ce3588724ad13b724e56456e314ecd9d7dfe42e661ecc896527c54c30",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :squashfs)
      => "e290facde9612ae5e2699d756885469c2953e90e19b782c49c13e9e2c1074fd6",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :targz)
      => "b0389a1f36e18d939ccb16a6a8c03a60bff9f2b106a6d04feb616e15902431fa",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :squashfs)
      => "03f4d8b3d43efbb6b9beba6b93d51de0d15e2a64fc90e36f2e25da0b81981c12",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:i686, libc=:glibc), :targz)
      => "aadf03557b6db143723c29fc3f2ffd1ea17129553338819d5d87c3b147f2dea5",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:i686, libc=:glibc), :squashfs)
      => "80a35afe60d488551f0d30181e8b54e7bae4a51d488388c8ebf442d0af2d9f18",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:i686, libc=:musl), :targz)
      => "de98187c6b6b9645367794fbcea61daae893ffb31bd4297590760e0106326afd",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:i686, libc=:musl), :squashfs)
      => "4311d9226c683acaf116ed7728f7b0718f14bcabe817a711bead9ae5eba6169b",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Windows(:i686), :targz)
      => "a3f289cd47b9cb0e3fb922f759de7ec2a642da3285d732fd03cb81342edaa244",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Windows(:i686), :squashfs)
      => "9bb8d239379b10a4a9c4819e6feece2aac3bd76703ff8311efb6918639dc6866",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:powerpc64le, libc=:glibc), :targz)
      => "32b866345501092b0bddb183433afee1e3b009dbf69ba0ba3a956a611bb19f9b",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:powerpc64le, libc=:glibc), :squashfs)
      => "ade1aa6ca9a3c716de9b1e77378afdf54ab0742725b2f8334da5f2af6e16378f",
    CompilerShard("BaseCompilerShard", v"2018.8.27", MacOS(:x86_64), :targz)
      => "419afc50422e78f447a2cf94eff8885cb1877be4726c45c61bf6ba4f96846225",
    CompilerShard("BaseCompilerShard", v"2018.8.27", MacOS(:x86_64), :squashfs)
      => "661db726306406d05098c360a845ebc0fd43fcc5dfe6286a6eed748934b0c718",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:x86_64, libc=:glibc), :targz)
      => "f954c735812edff98b16ccafcb219b5218c32361c993fb43da3fa7b8797ac6e2",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:x86_64, libc=:glibc), :squashfs)
      => "48cc87f76dc301598e9930161d0044417101ebc8f2c78b21ead1b6ffdaded59b",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:x86_64, libc=:musl), :targz)
      => "a18044939a46f1aaa7866bb74d781ce96f2113abb45a4c02e2ad6bffa73d6515",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Linux(:x86_64, libc=:musl), :squashfs)
      => "88a3d4e3e2b13750668b2f529bc8739ca8b4b5caecef58e183320361cc13fb66",
    CompilerShard("BaseCompilerShard", v"2018.8.27", FreeBSD(:x86_64), :targz)
      => "001a79b6e7955aecba8237cb4ff40b28ec86b1387bd642313304d0753621bf80",
    CompilerShard("BaseCompilerShard", v"2018.8.27", FreeBSD(:x86_64), :squashfs)
      => "59a282d5db131e483117ea16dc2dd64426940b0fa4a43da9d427fa468b1b6648",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Windows(:x86_64), :targz)
      => "fea10bca46c9a6c5e833efc59a8864b5c9b44d5d8de00f5161dc8e46b8802aab",
    CompilerShard("BaseCompilerShard", v"2018.8.27", Windows(:x86_64), :squashfs)
      => "1c8889aa8438e744690ff1222f2820a4f551fdaff6fc6bffda4269d0d34491d4",
    CompilerShard("GCC", v"4.8.5", Linux(:aarch64, libc=:glibc), :targz)
      => "9c0a5daef271d434315b3eaa603f49c1cf81891f63b0b3cfe0fc30291b339db6",
    CompilerShard("GCC", v"4.8.5", Linux(:aarch64, libc=:glibc), :squashfs)
      => "f32b46d539dc31ac7012e043c7c5ed3ecb202fe3baa30d8dea69e0a10300cc14",
    CompilerShard("GCC", v"4.8.5", Linux(:aarch64, libc=:musl), :targz)
      => "8537c80aaad79ba7d312e3150122b64d3a31037a1be3869cb154e7bdbf196b0a",
    CompilerShard("GCC", v"4.8.5", Linux(:aarch64, libc=:musl), :squashfs)
      => "e4260da1fb209b211f9b5b9dceeb8bf91276bb3a6d866299eec1ddcb876d227b",
    CompilerShard("GCC", v"4.8.5", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :targz)
      => "9064f67f368e0ffe3f59b2faea0e80dad33e5faa1f7c76657d99308471a6b43b",
    CompilerShard("GCC", v"4.8.5", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :squashfs)
      => "cc129e96783cf4c62c5e427f6e25eba52125a3f289b31b20566ae3f9c0e6ea9a",
    CompilerShard("GCC", v"4.8.5", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :targz)
      => "a13af0df5d01efd8d475240362c28db542a5437520ae70cdfb57fdfcbf7160b3",
    CompilerShard("GCC", v"4.8.5", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :squashfs)
      => "538850bf48de96379acb1424830fd82bf924558e8b5e730538b81dedff8a26b6",
    CompilerShard("GCC", v"4.8.5", Linux(:i686, libc=:glibc), :targz)
      => "ecd906c1ca299f390ca6d43159de89f8a6219aa69635d70b093ecfbe7d08b142",
    CompilerShard("GCC", v"4.8.5", Linux(:i686, libc=:glibc), :squashfs)
      => "a175ad638884597212aac43a19d1a0d39360ef8ab7c2bc69571a87e45aabeca6",
    CompilerShard("GCC", v"4.8.5", Linux(:i686, libc=:musl), :targz)
      => "7e08633a6c17df50284590af1282b1fe52ac5f20621c9313a5aac17de1a94bdd",
    CompilerShard("GCC", v"4.8.5", Linux(:i686, libc=:musl), :squashfs)
      => "a8099b7e24aa5452ddaf52671ba36254ae266854d7a31bfb2332482d362dcf7f",
    CompilerShard("GCC", v"4.8.5", Windows(:i686), :targz)
      => "268ac30e77bdf648ce299b3dedcaa7de19a0dbdb94a532a4322bae0338a9678c",
    CompilerShard("GCC", v"4.8.5", Windows(:i686), :squashfs)
      => "bf55cf63a28fd6c1fba90b32030f397d0b8825432016cadd63f38396bf65471a",
    CompilerShard("GCC", v"4.8.5", Linux(:powerpc64le, libc=:glibc), :targz)
      => "375999048c42ea583ec5d0dbcd365a09f7ab41ceeab5bc3b895235e5821ad1a0",
    CompilerShard("GCC", v"4.8.5", Linux(:powerpc64le, libc=:glibc), :squashfs)
      => "632c691d7a69c1345d6294253d429f620ad89b24e977403ca40f5a831a5947c0",
    CompilerShard("GCC", v"4.8.5", MacOS(:x86_64), :targz)
      => "9934e40e2c4689d707ad44f3a2dc76ce78633054799654333caf7e91f53bacc1",
    CompilerShard("GCC", v"4.8.5", MacOS(:x86_64), :squashfs)
      => "e42e2f09f80b0dd95e3f476dfab04d4de67d07ae89da121ba1a9267886002c92",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :targz)
      => "50b4b0276db194c49f5ebbd22a7e3e1db70b853ee32cda160a873711320ca944",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:glibc), :squashfs)
      => "e01014d26c16a1cd7a1b07f399feb34baf966c50b4e262932acbb576ac91a3e8",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:musl), :targz)
      => "64645dcfe1f2232319de011a129234adf450c8c2229b9352ad4a647164d634c3",
    CompilerShard("GCC", v"4.8.5", Linux(:x86_64, libc=:musl), :squashfs)
      => "0a935f5837966531ea40d3c2adde3b73109bae62a9b7f108e9f3281107e341ff",
    CompilerShard("GCC", v"4.8.5", FreeBSD(:x86_64), :targz)
      => "93bc6b868941275b155fae0f0896471b7038c304cbdc9572476402b4b394fddc",
    CompilerShard("GCC", v"4.8.5", FreeBSD(:x86_64), :squashfs)
      => "e6e32954135d00ffa6cc4511d68de2fbb6470a0923dd88e750a97311ae35fc0d",
    CompilerShard("GCC", v"4.8.5", Windows(:x86_64), :targz)
      => "d0c3646df0e8bdd4f522cec6ae4ddff73c9b904c8cdaaa3087759671bc8746c5",
    CompilerShard("GCC", v"4.8.5", Windows(:x86_64), :squashfs)
      => "a4e76688329be4d2f611bbd6d66dce3e64d8f85917d06737f50124a2dcc1be31",
    CompilerShard("GCC", v"7.1.0", Linux(:aarch64, libc=:glibc), :targz)
      => "174abfea98864b5fc5bbf722b4deb26cfb46db9f9d2ea6cbeec856e22d364ef2",
    CompilerShard("GCC", v"7.1.0", Linux(:aarch64, libc=:glibc), :squashfs)
      => "57d9d125cbd792256ea23b35bec1b7e3d2d35e6e809ab5d7ef9f44564e45ec89",
    CompilerShard("GCC", v"7.1.0", Linux(:aarch64, libc=:musl), :targz)
      => "3df54c2ad769235e04b2ae9f2ed9d987a9d36dbbc05efaec5ebe251304bf1850",
    CompilerShard("GCC", v"7.1.0", Linux(:aarch64, libc=:musl), :squashfs)
      => "2262a7f481e49940506d875da9b20cf65ece6a3a181aeaef633eea9bfeced249",
    CompilerShard("GCC", v"7.1.0", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :targz)
      => "c280d38c2a67af3f146c86a41220ae327b915d6d86420eea2f46f481a3939bc6",
    CompilerShard("GCC", v"7.1.0", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :squashfs)
      => "5333e6d49807df47c69443b4215acbfdd57e7a3cc1fafee85234f823a5c0b0fc",
    CompilerShard("GCC", v"7.1.0", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :targz)
      => "67fd2531cd2dca2b096591bbd06ea6dbe0ed5774e5477529c4526962a0dd65be",
    CompilerShard("GCC", v"7.1.0", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :squashfs)
      => "f82226315c290c2970f8fba81dc8cbb372a90354133b5060a8e1eac60b000435",
    CompilerShard("GCC", v"7.1.0", Linux(:i686, libc=:glibc), :targz)
      => "0dae432601bf78af74483712ce4a202887bc069bfcbfe9f1edf2546ff77cb0a4",
    CompilerShard("GCC", v"7.1.0", Linux(:i686, libc=:glibc), :squashfs)
      => "8e334aaad393ee62283c6708f1c55558a565be09751fb985f4794fb87b0d7372",
    CompilerShard("GCC", v"7.1.0", Linux(:i686, libc=:musl), :targz)
      => "aaac22f4b634797f8130781a99be646295ff9ca037d25e21f390339f54bd94cc",
    CompilerShard("GCC", v"7.1.0", Linux(:i686, libc=:musl), :squashfs)
      => "61ee8c472b809d23ca6ca92e9c6fc7e240e8e404450de99f93e1f302bcb7e354",
    CompilerShard("GCC", v"7.1.0", Windows(:i686), :targz)
      => "8a864d6e8a6588734f7b6e29c594112f25e463a6502ac4bac781b23ad8586d28",
    CompilerShard("GCC", v"7.1.0", Windows(:i686), :squashfs)
      => "11941e427c9dce00dc39831cc3f5fe64307b53e20fe3944eacc21e2c56dca1de",
    CompilerShard("GCC", v"7.1.0", Linux(:powerpc64le, libc=:glibc), :targz)
      => "d13a10ed9d04843393d5886b0fa98f93427c166df9d989d8d146240aa322b02a",
    CompilerShard("GCC", v"7.1.0", Linux(:powerpc64le, libc=:glibc), :squashfs)
      => "5e1d273ba5737c6bdd4cc0a89e497b9ecca78fafd720b69d5f6a0df12ea227d8",
    CompilerShard("GCC", v"7.1.0", MacOS(:x86_64), :targz)
      => "b6ea728cf8cff3bbf09610c6d1ab615a4de57e699c23f245f343af2044d33ce0",
    CompilerShard("GCC", v"7.1.0", MacOS(:x86_64), :squashfs)
      => "51caf6f3bc7cbe7aea67caf437c0e051fa3590b3def772dd73fc6c7327a0d998",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :targz)
      => "5258c5f1e4404955db9677540a1d072df0972268e79eb52d7646cbe42a0482f5",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:glibc), :squashfs)
      => "c32352ce3575a6bb78ce5bdf71fa604224fcaf3a936aca2d93154ab62865a6ab",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:musl), :targz)
      => "2a7e72f0a2a5e4724835a03fb24a715379ed52165e025aa2f5251a91d352a69b",
    CompilerShard("GCC", v"7.1.0", Linux(:x86_64, libc=:musl), :squashfs)
      => "4560f4309348d040599326363e1fa3dfe081b7a34298bf01ae1ec315aa99ef5c",
    CompilerShard("GCC", v"7.1.0", FreeBSD(:x86_64), :targz)
      => "3b1db8a4ef78faed33a6a3e682ea0bc6c6e30c95e530cbd0a2333945b69c2c5e",
    CompilerShard("GCC", v"7.1.0", FreeBSD(:x86_64), :squashfs)
      => "e4c281b7d3865e9d7f5f1cdeefc18d05c26bcdf3c83103264ecd4ee2432dbff0",
    CompilerShard("GCC", v"7.1.0", Windows(:x86_64), :targz)
      => "d0c89449632e425c0bf99b7b2670b2f8f8a021cc22168c8c7806832b7100bc96",
    CompilerShard("GCC", v"7.1.0", Windows(:x86_64), :squashfs)
      => "1e2a7c1ddf9a432faf9342fe24e032cf286a05fc1ecff006a23d9c333ca1ba6c",
    CompilerShard("GCC", v"8.1.0", Linux(:aarch64, libc=:glibc), :targz)
      => "4e844e452d8fb56de1270bafa44b262925254e68644d7b60ae5a251b9b5d1283",
    CompilerShard("GCC", v"8.1.0", Linux(:aarch64, libc=:glibc), :squashfs)
      => "53402897d862a91baf66baa049d63e952e1a02ffc467ddbfc1f8c2a7ba8543b5",
    CompilerShard("GCC", v"8.1.0", Linux(:aarch64, libc=:musl), :targz)
      => "5cf1c2c06c0746968d9270eae0867d144bfcf1e886debcd7ff217a8269b79582",
    CompilerShard("GCC", v"8.1.0", Linux(:aarch64, libc=:musl), :squashfs)
      => "bacd60419635ac2b18d2f529794113fa751b570cc803344b9f6e5e8ad680c4ba",
    CompilerShard("GCC", v"8.1.0", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :targz)
      => "80cdb3258097efee16c0236ec7707b12f76f8f03f1d5a0108303a30628ea45b2",
    CompilerShard("GCC", v"8.1.0", Linux(:armv7l, libc=:glibc, call_abi=:eabihf), :squashfs)
      => "8ef30f4614ad0e09f5fb4663c4b5d662d2ece201b7e78e1b061e5b7cd48f593d",
    CompilerShard("GCC", v"8.1.0", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :targz)
      => "575c25cfb5152d8b927f572306032213b953c749b25bc1f5653193b166510029",
    CompilerShard("GCC", v"8.1.0", Linux(:armv7l, libc=:musl, call_abi=:eabihf), :squashfs)
      => "f565e4031857a40563d35a9d6b04f4eea75c642f1b2bdc31f1003c94dd0d6e7a",
    CompilerShard("GCC", v"8.1.0", Linux(:i686, libc=:glibc), :targz)
      => "4a3f4ad0d6679ad87c1e48e6bddf2465c17ee630957c8a3ed9f0ef734d1b8c4b",
    CompilerShard("GCC", v"8.1.0", Linux(:i686, libc=:glibc), :squashfs)
      => "8111e3c4d3b1a868302463f6ef3a43d6b3437351e5f62b5ac6dbe8699d2400e7",
    CompilerShard("GCC", v"8.1.0", Linux(:i686, libc=:musl), :targz)
      => "b5efa505ecfc73504b6a5127a40c95f38b810c138be282978ab0862191108a21",
    CompilerShard("GCC", v"8.1.0", Linux(:i686, libc=:musl), :squashfs)
      => "f406becf6e1393df7fc13cb837d7180173a276b227a58586468c932356fa774b",
    CompilerShard("GCC", v"8.1.0", Windows(:i686), :targz)
      => "02a73587b0638b593f3683b356a5e86d743c90d5b383619b77930a73f4e8112e",
    CompilerShard("GCC", v"8.1.0", Windows(:i686), :squashfs)
      => "e2ca9c415c60dcfb81bd90b1eae9ba52e14870e6bf388862f03952106e32be98",
    CompilerShard("GCC", v"8.1.0", Linux(:powerpc64le, libc=:glibc), :targz)
      => "d0b9bc3c221df8232ef61170c726ae4da0ef2464eaa8e9e7ec863bc3e31e69cf",
    CompilerShard("GCC", v"8.1.0", Linux(:powerpc64le, libc=:glibc), :squashfs)
      => "0c1f3802b122f740bf93201e6541667f85dc1a65f3e1b8fcc8cfeaa9fd5820fc",
    CompilerShard("GCC", v"8.1.0", MacOS(:x86_64), :targz)
      => "df31361168271f46c2b0daf7eea0eebe1ffcc40191881217eb6ca16e4f19a74f",
    CompilerShard("GCC", v"8.1.0", MacOS(:x86_64), :squashfs)
      => "b8de8bcf6f2fe29fb44d6f1dbe2c9811c5b5f1a32710b8928e10d6548e44b6b4",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :targz)
      => "3918c797b5812cc1ee2ff996301f81b766f99b6b0fbc6a512f13762a613272f7",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:glibc), :squashfs)
      => "c0d1f9fd061ec4f198d7620b8921627793fd385b203684d243fc729bfe934729",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:musl), :targz)
      => "793bbba8d44721696e8dc38e83c020d801a7b2c5c13629f99645e97c6569d269",
    CompilerShard("GCC", v"8.1.0", Linux(:x86_64, libc=:musl), :squashfs)
      => "23c3973eec122b42ef0468004d2be22d00a33a320f26ed10736fbcbc98d3c12c",
    CompilerShard("GCC", v"8.1.0", FreeBSD(:x86_64), :targz)
      => "79abc8e6c7896155e9281321072cb09b782820275c6a71a929145339bd95bcf7",
    CompilerShard("GCC", v"8.1.0", FreeBSD(:x86_64), :squashfs)
      => "e0d247d967c30c3a54173be349d4639400e399d794bb6365cc6d53581573d6f1",
    CompilerShard("GCC", v"8.1.0", Windows(:x86_64), :targz)
      => "9b5512042a7923a02c7334532ac3bde2300b7e3dc68a02a70a7a7e7acf189baa",
    CompilerShard("GCC", v"8.1.0", Windows(:x86_64), :squashfs)
      => "c0231c461f37281110e4dc64e78a931934a90a19617b0802b4733dd00067a9cd",
    CompilerShard("LLVM", v"6.0.1", Linux(:x86_64, libc=:glibc), :targz)
      => "9df753f91b098cc55892f08e65de70734019066b6c368f961b0342594eb4d9ad",
    CompilerShard("LLVM", v"6.0.1", Linux(:x86_64, libc=:glibc), :squashfs)
      => "702893921da7c02fb5d0b23d72af502c06ea8d5fedd1ee6d96c0f72eae0eae46",
    CompilerShard("Rootfs", v"2018.8.27", Linux(:x86_64, libc=:glibc), :targz)
      => "ab0d5e6743762621e3fca74a55b7acff15738c7cd0d682ea99280a82f6eeda5b",
    CompilerShard("Rootfs", v"2018.8.27", Linux(:x86_64, libc=:glibc), :squashfs)
      => "ae37cf5c4ff1548c913a57de9860de2de71f90cdbffa8c751a809cbec98d9476",
)
