name: CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

env:
  BINARYBUILDER_AUTOMATIC_APPLE: true

jobs:
  test:
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
      matrix:
        include:
          # Add a job that uses the privileged builder with squashfs shards
          - env:
              BINARYBUILDER_RUNNER: privileged
              BINARYBUILDER_USE_SQUASHFS: true

          # Add a job that uses the unprivileged builder with unpacked shards
          - env:
              BINARYBUILDER_RUNNER: unprivileged
              BINARYBUILDER_USE_SQUASHFS: false

          # Add a job that uses the docker builder with unpacked shards
          - env:
              BINARYBUILDER_RUNNER: docker
              BINARYBUILDER_USE_SQUASHFS: false
    steps:
      - uses: actions/checkout@2036a08e25fa78bbd946711a407b529a0a1204bf # v2.3.2
      - uses: julia-actions/julia-buildpkg@9ae2dda33d6efd1a7b5d43ec7377b7d20490a51b # v1.0.0
      # - name: Setup git user
      #   run: |
      #     git config --global user.name "Binary Builder"
      #     git config --global user.email "binary.builder@julialang.org"
      - uses: julia-actions/julia-runtest@642d7a4c3b5078681a278015c40232a763d3756a # v1.0.0
      - uses: julia-actions/julia-processcoverage@033f48081796acf509d3dd406127b5b7eee3d2d3 # v1.1.0
